// ONE TILE - the 24 rooms. Legend in sim.js. Guard routes: U D L R step, u d l r turn, . wait,
// a number repeats the letter before it (R4 = RRRR). Cameras: 'D3 DR2' = face D 3 ticks, then DR 2.
// Lasers: tiles x1,y1..x2,y2, on while (t + phase) % period < on.
// Par and minimum ticks are computed by tools/solve.mjs into pars.js.

export const THEMES = ['bank', 'museum', 'casino', 'penthouse'];

export const LEVELS = [
  // ---------------- BANK ----------------
  {
    name: 'First Job', theme: 'bank',
    tip: 'Hold WASD to run. Grab the gold, stand next to the safe until it cracks, then out the EXIT door.',
    map: [
      '##########',
      '#S.......#',
      '#.######.#',
      '#.#...c#.#',
      '#.#.$..#.#',
      '#.#....#.#',
      '#.##.###.#',
      '#........#',
      '####X#####',
    ],
  },
  {
    name: 'Night Shift', theme: 'bank',
    tip: 'Guards see the yellow cone. Wait for his back, then go.',
    map: [
      '#############',
      '#S....#.....#',
      '#.....#..$..#',
      '#.....#.....#',
      '#..........G#',
      '#.....#.....#',
      '#.....#.....#',
      '#########X###',
    ],
    guards: [{ face: 'L', route: 'L4 . R4 l' }],
  },
  {
    name: 'Round and Round', theme: 'bank',
    tip: 'Cash bags are optional, but you need them for the third star. Never get in front of a guard.',
    map: [
      '################',
      '##.............#',
      '##.####$######.#',
      '#S.###########.#',
      '##.###########.#',
      '##G###########.#',
      '##.###########.#',
      '##............c#',
      '########X#######',
    ],
    guards: [{ face: 'U', route: 'U4 R12 D6 L12 U2' }],
  },

  {
    name: 'Rush Hour', theme: 'bank',
    tip: 'Two guards, two lanes. Walk right behind a guard: he only looks ahead.',
    map: [
      '#############',
      '#S..........#',
      '#########.###',
      '#G..........#',
      '###.#########',
      '#..........G#',
      '#########.###',
      '#c..........#',
      '#X####$######',
    ],
    guards: [{ face: 'R', route: 'R10 L10 r', skip: 4 }, { face: 'L', route: 'L10 R10 l', skip: 13 }],
  },
  {
    name: 'Heads Up', theme: 'bank',
    tip: 'This guard stands still and turns his head. The safe blocks his view: crack it from behind.',
    map: [
      '#########X#',
      '#S...#....#',
      '#....#....#',
      '#.........#',
      '#....G..$.#',
      '#.........#',
      '#....#....#',
      '#c...#....#',
      '###########',
    ],
    guards: [{ face: 'L', route: 'l3 u1 r1 d2 l', r: 5 }],
  },
  {
    name: 'The Vault', theme: 'bank',
    tip: 'Cracking can be done in pieces. Step away when he looks, come back and finish.',
    map: [
      '###############',
      '#S....#.......#',
      '#.....#.o...o.#',
      '#..G.....$....#',
      '#.....#.o...o.#',
      '###.###.......#',
      '#c.....#..G...#',
      '#......#......#',
      '#####X#########',
    ],
    guards: [{ face: 'R', route: 'R4 . L4 . r' }, { face: 'U', route: 'U5 . D5 . u' }],
  },
  // ---------------- MUSEUM ----------------
  {
    name: 'Say Cheese', theme: 'museum',
    tip: 'Cameras sweep on a loop. Statues block their view, glass cases do not.',
    map: [
      '#######@#######',
      '#S............#',
      '#.............#',
      '#...o.....o...#',
      '#.............#',
      '#.............#',
      '#....T...T....#',
      '#c...........$#',
      '###########X###',
    ],
    cams: [{ seq: 'DL3 D2 DR3 D2', r: 7 }],
  },
  {
    name: 'Glass Cases', theme: 'museum',
    tip: 'Glass cases stop you, not his eyes.',
    map: [
      '###############',
      '#S..T....T....#',
      '#...T....T..$.#',
      '#G............#',
      '#...T....T....#',
      '#...T....T..c.#',
      '#.............@',
      '#######X#######',
    ],
    guards: [{ face: 'R', route: 'R12 D3 L12 U3 r', skip: 26 }],
    cams: [{ seq: 'L4 UL2 L2 DL2', r: 6, skip: 8 }],
  },
  {
    name: 'Potted Ferns', theme: 'museum',
    tip: 'Plants are hiding spots. While you stand in one, no cone can see you.',
    map: [
      '################',
      '#####h####h#####',
      '#S....G........#',
      '##############.#',
      '#...........$..#',
      '#.......c......#',
      '#######X########',
    ],
    guards: [{ face: 'R', route: 'R7 . L11 . R4' }],
  },
  {
    name: 'Locker Room', theme: 'museum',
    tip: 'Two guards chase each other round the ring. Lockers hide you while one walks past.',
    map: [
      '####k#####k####',
      '#......G......#',
      '#.#####$#####.#',
      '#.###########.#',
      'S.###########.k',
      '#.###########.#',
      '#.###########.#',
      '#......G......#',
      '####k##X##k####',
    ],
    guards: [{ face: 'L', route: 'L6 D6 R12 U6 L6' }, { face: 'R', route: 'R6 U6 L12 D6 R6' }],
  },
  {
    name: 'Night Watch', theme: 'museum',
    tip: 'Plants are islands. Hop from one to the next while the cameras look away.',
    map: [
      '####@#####@####',
      '#S............#',
      '#.............#',
      '#..o.......o..#',
      '#.....h.h.....#',
      '#..h.......h..#',
      '#......$......#',
      '#..h.......h..#',
      '#......G.....g#',
      '#######X#######',
    ],
    guards: [{ face: 'R', route: 'R6 . L12 . R6' }],
    cams: [{ seq: 'D2 DR2 D2 DL2', r: 7 }, { seq: 'DL2 D2 DR2 D2', r: 7 }],
  },
  {
    name: 'The Diamond', theme: 'museum',
    tip: 'The diamond sits in a glass case. Glass hides nothing from the camera.',
    map: [
      '#####@#########',
      '#S...........h#',
      '#.TTT.TTT.....#',
      '#.T.....T..o..#',
      '#.T..g..T.....#',
      '#.T.....T..o..#',
      '#.TTTTTTT.....#',
      '#.........$...#',
      '#........G....#',
      '#X#############',
    ],
    guards: [{ face: 'L', route: 'L8 U7 R8 D7 l' }],
    cams: [{ seq: 'DL3 L2 DL2 D2 DR3 R2 DR2 D2', r: 8 }],
  },
  // ---------------- CASINO ----------------
  {
    name: 'Red Lines', theme: 'casino',
    tip: 'Lasers blink on a timer, all together here. Be between them when they switch on.',
    map: [
      '###############',
      '#S...........c#',
      '#.............#',
      '#.............X',
      '#.............#',
      '#...........$.#',
      '###############',
    ],
    lasers: [
      { x1: 4, y1: 1, x2: 4, y2: 5, period: 6, on: 3, phase: 3 },
      { x1: 7, y1: 1, x2: 7, y2: 5, period: 6, on: 3, phase: 3 },
      { x1: 10, y1: 1, x2: 10, y2: 5, period: 6, on: 3, phase: 3 },
    ],
  },
  {
    name: 'Slot Alley', theme: 'casino',
    tip: 'Slot machines block sight. Lasers and a guard keep different time: find the beat where both are kind.',
    map: [
      '###############',
      '#S...........c#',
      '#.oo.oo.oo.oo.#',
      '#.oo.oo.oo.oo.#',
      '#......G......#',
      '#.oo.oo.oo.oo.#',
      '#.oo.oo.oo.oo.#',
      '#............$#',
      '#######X#######',
    ],
    guards: [{ face: 'R', route: 'R6 . L12 . R6' }],
    lasers: [
      { x1: 1, y1: 2, x2: 1, y2: 3, period: 6, on: 4, phase: 0 },
      { x1: 4, y1: 2, x2: 4, y2: 3, period: 6, on: 4, phase: 1 },
      { x1: 7, y1: 2, x2: 7, y2: 3, period: 6, on: 4, phase: 4 },
      { x1: 10, y1: 2, x2: 10, y2: 3, period: 6, on: 4, phase: 4 },
      { x1: 13, y1: 2, x2: 13, y2: 3, period: 6, on: 4, phase: 1 },
      { x1: 1, y1: 5, x2: 1, y2: 6, period: 6, on: 4, phase: 5 },
      { x1: 4, y1: 5, x2: 4, y2: 6, period: 6, on: 4, phase: 4 },
      { x1: 7, y1: 5, x2: 7, y2: 6, period: 6, on: 4, phase: 1 },
      { x1: 10, y1: 5, x2: 10, y2: 6, period: 6, on: 4, phase: 2 },
      { x1: 13, y1: 5, x2: 13, y2: 6, period: 6, on: 4, phase: 1 },
    ],
  },
  {
    name: 'High Roller', theme: 'casino',
    tip: 'Coloured doors open when you walk into them, and block sight while shut.',
    map: [
      '###############',
      '#S...#.......r#',
      '#.............#',
      '#....#.T...T.c#',
      '#....#....G...#',
      '#....###R######',
      '#....#........#',
      '#....#..$.....#',
      '#....#........#',
      '##X############',
    ],
    guards: [{ face: 'L', route: 'l2 u3 r3 d3 l' , r: 5 }],
  },
  {
    name: 'Card Sharp', theme: 'casino',
    tip: 'Two doors, two ways round. Pick the quiet one.',
    map: [
      '###############',
      '#S....#......r#',
      '#.....#.......#',
      '#.............#',
      '#.....######R##',
      '#.....#b.....##',
      '#.....#......##',
      '#####B#########',
      '#.......c.$...#',
      '#X#############',
    ],
    lasers: [
      { x1: 9, y1: 1, x2: 9, y2: 3, period: 6, on: 4, phase: 0 },
      { x1: 11, y1: 1, x2: 11, y2: 3, period: 6, on: 4, phase: 3 },
      { x1: 9, y1: 5, x2: 9, y2: 6, period: 4, on: 2, phase: 0 },
      { x1: 2, y1: 8, x2: 4, y2: 8, period: 6, on: 3, phase: 0 },
    ],
  },
  {
    name: 'Eye in the Sky', theme: 'casino',
    tip: 'Two cameras, one guard. The tile right under a camera is always watched.',
    map: [
      '#####@#####@####',
      '#S............y#',
      '#..TT..TT..TT..#',
      '#..TT..TT..TT..#',
      '#G.............#',
      '#..TT..TT..TT..#',
      '#..TT..TT..TT..#',
      '#..............#',
      '#######Y########',
      '#...$.........cX',
      '################',
    ],
    guards: [{ face: 'R', route: 'R13 D3 L13 U3 r', skip: 24 }],
    cams: [{ seq: 'D2 DR2 D2 DL2', r: 6 }, { seq: 'DL2 D2 DR2 D2', r: 6, skip: 3 }],
  },
  {
    name: 'House Edge', theme: 'casino',
    tip: 'Everything the casino has. Take it slow, wait for the gaps.',
    map: [
      '################',
      '#S....#...@....#',
      '#.....#........#',
      '#..G..R...TT.r.#',
      '#.....#...TT...#',
      '###.###........#',
      '#.....#####B####',
      '#.c...........$#',
      '#............G.#',
      '######X#########',
    ],
    guards: [{ face: 'D', route: 'D4 . U4 . d' }, { face: 'L', route: 'L12 . R12 . l' }],
    cams: [{ seq: 'D3 DR2 R2 DR2', r: 6 }],
    lasers: [
      { x1: 7, y1: 2, x2: 7, y2: 5, period: 6, on: 3, phase: 0 },
    ],
  },
  // ---------------- PENTHOUSE ----------------
  {
    name: 'Sky Lobby', theme: 'penthouse',
    tip: 'This one looks over his shoulder. Follow, but stop before he turns.',
    map: [
      '################',
      '###h####h####h##',
      '#SG............#',
      '#############.##',
      '#c.............X',
      '######$#########',
    ],
    guards: [{ face: 'R', route: 'R3 l2 r R4 l2 r R4 l . r L11 . r' }],
  },
  {
    name: 'Infinity Pool', theme: 'penthouse', tStyle: 'pool',
    tip: 'Water stops feet, not eyes.',
    map: [
      '################',
      '#S.............#',
      '#.TTTTTTTTTTTT.#',
      '#.TTTTTTTTTTTT.#',
      '#.TTTTTTTTTTTT.#',
      '#.............G#',
      '#.h....o....h..#',
      '#..............#',
      '#.......$....c.#',
      '##X####@########',
    ],
    guards: [{ face: 'U', route: 'U4 L13 D4 R13 u', skip: 20 }],
    cams: [{ seq: 'U3 UL3 U3 UR3', r: 7, skip: 6 }],
    lasers: [{ x1: 1, y1: 7, x2: 14, y2: 7, period: 8, on: 4, phase: 0 }],
  },
  {
    name: 'Art Collection', theme: 'penthouse',
    tip: 'Closets hide you. Duck in, let him pass, keep going.',
    map: [
      '################',
      '#S..#k..r..k#.b#',
      '#...#.......#..#',
      '#.......o...R..#',
      '#...#.......#..#',
      '#...#...G...@..#',
      '##B#############',
      '#c............##',
      '########$####X##',
    ],
    guards: [{ face: 'L', route: 'L3 U3 R6 D3 L3' }],
    cams: [{ seq: 'L3 UL3', r: 6 }],
  },
  {
    name: 'Panic Room', theme: 'penthouse',
    tip: 'The panic room lasers never stop. Find the tiles between the beats.',
    map: [
      '################',
      '#S.............#',
      '#..o.......o...#',
      '#....######....#',
      '#....#....#....#',
      '#..G......#..c.#',
      '#....#..$.#....#',
      '#....######....#',
      '#..o.......o...#',
      '#######X########',
    ],
    guards: [{ face: 'R', route: 'r3 u2 l2 d2 r' }],
    lasers: [
      { x1: 5, y1: 5, x2: 5, y2: 5, period: 6, on: 4, phase: 0 },
      { x1: 7, y1: 4, x2: 7, y2: 6, period: 4, on: 2, phase: 1 },
      { x1: 9, y1: 4, x2: 9, y2: 6, period: 4, on: 2, phase: 3 },
    ],
  },
  {
    name: 'Rooftop Garden', theme: 'penthouse',
    tip: 'Two gardeners on the night shift, one inside the other. Every hedge is a hiding place.',
    map: [
      '################',
      '#S.............#',
      '#.#h##.##.####.#',
      '#.#..........#.#',
      '#.#.##h##h##.#.#',
      '#...#...$..#...#',
      '#.#.##h##.##.#.#',
      '#.#.........G#.#',
      '#.####.##.##h#.#',
      '#......G......c#',
      '#######X########',
    ],
    guards: [{ face: 'L', route: 'L9 U4 R9 D4 l', skip: 6 }, { face: 'R', route: 'R7 U8 L13 D8 R6', skip: 16 }],
  },
  {
    name: 'The Big One', theme: 'penthouse',
    tip: 'The last job. The safe, the gem, every guard at once.',
    map: [
      '########@#######',
      '#S..#.........g#',
      '#...#.TT...TT..#',
      '#.......o.....G#',
      '#...#.TT...TT..#',
      '#...#..r.......#',
      '##R####Y########',
      '#k...#....#....#',
      '#..y.#..$......#',
      '#k..G#....#....#',
      '#############X##',
    ],
    guards: [{ face: 'L', route: 'L5 . R5 . l' }, { face: 'U', route: 'U2 l . r D2 . u' }],
    cams: [{ seq: 'DL3 D2 DR3 D2', r: 7, skip: 8 }],
    lasers: [
      { x1: 6, y1: 7, x2: 9, y2: 7, period: 6, on: 3, phase: 0 },
      { x1: 10, y1: 8, x2: 10, y2: 8, period: 5, on: 3, phase: 1 },
    ],
  },
];
