// Generated by tools/solve.mjs: par = all-loot minimum + max(2, 12%). Do not edit by hand.
export const PARS = [28,35,37,46,31,48,32,53,45,53,50,59,34,55,60,75,71,45,69,60,74,62,47,97];
export const MINS = [17,31,33,41,16,39,24,36,40,47,33,44,26,31,45,67,63,38,52,35,64,36,28,63];
