// The gear catalogue. Every entry is pure data: a price plus the colours and
// style flags the renderer already understands. Adding a jacket is one object
// here, not a change to the art code.
//
// Style brief: street. Slim and baggy denim, sweats, work jackets and
// bombers over a long tee, canvas skate shoes and flip flops, beanies and caps.
//
// BUILD, SKIN, EYES and the HAIR CUT are free. Those are who you are, not gear.

export const CATEGORIES = [
  { key: 'body', name: 'BUILD' },
  { key: 'skin', name: 'SKIN' },
  { key: 'eyes', name: 'EYES' },
  { key: 'hairstyle', name: 'HAIR CUT' },
  { key: 'haircolor', name: 'HAIR COLOUR' },
  { key: 'hat', name: 'HEADWEAR' },
  { key: 'face', name: 'GLASSES' },
  { key: 'shirt', name: 'SHIRTS' },
  { key: 'mid', name: 'SWEATERS' },
  { key: 'over', name: 'JACKETS' },
  { key: 'legs', name: 'LEGS' },
  { key: 'socks', name: 'SOCKS' },
  { key: 'shoes', name: 'SHOES' },
  { key: 'deck', name: 'DECKS' },
  { key: 'grip', name: 'GRIP' },
  { key: 'wheels', name: 'WHEELS' },
  { key: 'stamina', name: 'STAMINA' },
];

export const GEAR = {
  // --- STAMINA -------------------------------------------------------------
  // Popping costs something. Off the couch you get TWO before you have to roll
  // for a moment, and the ladder climbs from there to about sixteen. Starting
  // that low is what makes the first upgrade worth buying at all.
  //
  // `max` is how much you hold, `regen` how fast it comes back per second, and
  // `cost` a multiplier on what each pop takes. Every tier improves all three,
  // and the last one costs more than any board in the shop -- it is meant to be
  // the thing you are still saving for after you have bought the clothes.
  stamina: [
    { id: 'legs-1', name: 'OFF THE COUCH', price: 0, tag: 'six pops, then a breather',
      max: 34, regen: 9, cost: 1, c: ['#8a4a4a', '#5c2d2d', '#3a1c1c'] },
    { id: 'legs-2', name: 'SKATING WEEKENDS', price: 1200, tag: 'a bit more in the tank',
      max: 55, regen: 13, cost: 0.95, c: ['#8a6a3c', '#5f4726', '#3d2d16'] },
    { id: 'legs-3', name: 'EVERY DAY AFTER SCHOOL', price: 3200, tag: '',
      max: 85, regen: 18, cost: 0.9, c: ['#8a8a3c', '#5f5f26', '#3d3d16'] },
    { id: 'legs-4', name: 'ALL SUMMER', price: 7000, tag: 'you can feel the difference',
      max: 125, regen: 25, cost: 0.85, c: ['#5f8a3c', '#3f5f26', '#273d16'] },
    { id: 'legs-5', name: 'SPONSORED', price: 14000, tag: 'barely have to think about it',
      max: 180, regen: 33, cost: 0.78, c: ['#3c8a6a', '#265f47', '#163d2d' ] },
    { id: 'legs-6', name: 'PRO LEGS', price: 30000, tag: 'pop until you get bored',
      max: 260, regen: 45, cost: 0.7, c: ['#3c6a8a', '#26475f', '#162d3d'] },
  ],

  // --- who you are (free) ---------------------------------------------------
  body: [
    { id: 'body-slim', name: 'SLIM', price: 0, tag: 'narrow shoulders',
      build: { shoulder: 0.86, hip: 0.92, height: 1.0 } },
    { id: 'body-athletic', name: 'ATHLETIC', price: 0, tag: 'even',
      build: { shoulder: 1.0, hip: 1.0, height: 1.0 } },
    { id: 'body-curvy', name: 'CURVY', price: 0, tag: 'narrow shoulders, wider hips',
      build: { shoulder: 0.88, hip: 1.22, height: 0.97 } },
    { id: 'body-broad', name: 'BROAD', price: 0, tag: 'big through the chest',
      build: { shoulder: 1.24, hip: 1.06, height: 1.03 } },
    { id: 'body-short', name: 'PETITE', price: 0, tag: 'shorter, lighter',
      build: { shoulder: 0.84, hip: 0.98, height: 0.9 } },
    { id: 'body-tall', name: 'TALL', price: 0, tag: 'long legs',
      build: { shoulder: 1.02, hip: 0.94, height: 1.11 } },
  ],
  skin: [
    { id: 'skin-1', name: 'PORCELAIN', price: 0, tag: '', c: ['#ffe0c2', '#e0b28c', '#b3835d'] },
    { id: 'skin-2', name: 'FAIR', price: 0, tag: '', c: ['#ffd3a8', '#e0a877', '#ad7850'] },
    { id: 'skin-3', name: 'OLIVE', price: 0, tag: '', c: ['#e8b581', '#c08d5b', '#8f6338'] },
    { id: 'skin-4', name: 'TAN', price: 0, tag: '', c: ['#cf9560', '#a87043', '#7a4d2a'] },
    { id: 'skin-5', name: 'BROWN', price: 0, tag: '', c: ['#a56b41', '#7d4c2c', '#57331c'] },
    { id: 'skin-6', name: 'DEEP', price: 0, tag: '', c: ['#7a4a2c', '#57331c', '#3a2113'] },
    { id: 'skin-7', name: 'RICH', price: 0, tag: '', c: ['#5a3520', '#3f2415', '#28150c'] },
  ],
  eyes: [
    { id: 'eye-brown', name: 'BROWN', price: 0, tag: '', c: ['#4a2f1c', '#2c1b10'] },
    { id: 'eye-dark', name: 'NEAR BLACK', price: 0, tag: '', c: ['#2a2230', '#181320'] },
    { id: 'eye-hazel', name: 'HAZEL', price: 0, tag: '', c: ['#8a6a2c', '#5a441c'] },
    { id: 'eye-green', name: 'GREEN', price: 0, tag: '', c: ['#3f8a52', '#255a35'] },
    { id: 'eye-blue', name: 'BLUE', price: 0, tag: '', c: ['#3f7ab5', '#28527a'] },
    { id: 'eye-grey', name: 'GREY', price: 0, tag: '', c: ['#7d8894', '#525b66'] },
    { id: 'eye-amber', name: 'AMBER', price: 0, tag: '', c: ['#c98a2c', '#8f5c18'] },
    { id: 'eye-violet', name: 'VIOLET', price: 400, tag: 'unusual', c: ['#8a63c9', '#5c3f8f'] },
    { id: 'eye-red', name: 'RED', price: 900, tag: 'contacts, obviously', c: ['#c93f3f', '#8f2626'] },
  ],
  hairstyle: [
    { id: 'cut-short', name: 'SHORT', price: 0, tag: 'cropped, side part', style: 'short' },
    { id: 'cut-buzz', name: 'BUZZ CUT', price: 0, tag: 'grown out a bit', style: 'buzz' },
    { id: 'cut-curls', name: 'CURLY', price: 0, tag: 'big loose curls', style: 'curls' },
    { id: 'cut-afro', name: 'AFRO', price: 0, tag: 'round and full', style: 'afro' },
    { id: 'cut-waves', name: 'WAVES', price: 0, tag: 'short and textured', style: 'waves' },
    { id: 'cut-long', name: 'LONG', price: 0, tag: 'past the shoulder', style: 'long' },
    { id: 'cut-curlylong', name: 'LONG CURLS', price: 0, tag: 'ringlets, shoulder length', style: 'curlylong' },
    { id: 'cut-pony', name: 'PONYTAIL', price: 0, tag: 'tied back', style: 'pony' },
    { id: 'cut-bun', name: 'TOP KNOT', price: 0, tag: 'up out of the way', style: 'bun' },
    { id: 'cut-locs', name: 'LOCS', price: 0, tag: 'shoulder length', style: 'locs' },
    { id: 'cut-braids', name: 'BRAIDS', price: 0, tag: 'tight to the scalp', style: 'braids' },
    { id: 'cut-bald', name: 'SHAVED', price: 0, tag: 'nothing at all', style: 'bald' },
  ],
  haircolor: [
    { id: 'col-black', name: 'BLACK', price: 0, tag: '', c: ['#33303a', '#211f27'] },
    { id: 'col-brown', name: 'BROWN', price: 0, tag: '', c: ['#5a3a26', '#3d2618'] },
    { id: 'col-darkbrown', name: 'DARK BROWN', price: 0, tag: '', c: ['#3f2a1c', '#291a10'] },
    { id: 'col-auburn', name: 'AUBURN', price: 0, tag: '', c: ['#8a422a', '#5c2a19'] },
    { id: 'col-ginger', name: 'GINGER', price: 0, tag: '', c: ['#d2733a', '#9b4a22'] },
    { id: 'col-blonde', name: 'BLONDE', price: 0, tag: '', c: ['#e0bd6e', '#ab8a45'] },
    { id: 'col-platinum', name: 'PLATINUM', price: 0, tag: '', c: ['#f2ead2', '#bdb391'] },
    { id: 'col-grey', name: 'GREY', price: 0, tag: '', c: ['#b8b4c0', '#87838f'] },
    { id: 'col-bleach', name: 'BLEACHED', price: 250, tag: 'grown out roots', c: ['#f2e6c0', '#b9a77c'] },
    { id: 'col-green', name: 'GREEN', price: 400, tag: 'loud', c: ['#8ada6a', '#4f8f3c'] },
    { id: 'col-pink', name: 'PINK', price: 400, tag: 'louder', c: ['#f083b5', '#b4507f'] },
    { id: 'col-blue', name: 'BLUE', price: 550, tag: 'electric', c: ['#6fb6e8', '#3d78ab'] },
    { id: 'col-purple', name: 'PURPLE', price: 550, tag: '', c: ['#a37ce0', '#6d55ad'] },
    { id: 'col-red', name: 'FIRE RED', price: 700, tag: '', c: ['#e0503f', '#9b2f26'] },
    { id: 'col-teal', name: 'TEAL', price: 700, tag: '', c: ['#5fc0c9', '#347782'] },
  ],

  // --- head -----------------------------------------------------------------
  hat: [
    { id: 'hat-none', name: 'NOTHING', price: 0, tag: 'just hair', kind: 'none', c: ['#000', '#000'] },
    { id: 'hat-cap', name: 'FIVE PANEL', price: 0, tag: 'stock', kind: 'cap', c: ['#7fd4e8', '#4a9cb5'] },
    { id: 'hat-beanie', name: 'BEANIE', price: 300, tag: 'cuffed', kind: 'beanie', c: ['#d2603f', '#9b3f2a'] },
    { id: 'hat-beanie-blk', name: 'BLACK BEANIE', price: 500, tag: 'pulled down', kind: 'beanie', c: ['#48434f', '#2f2b36'] },
    { id: 'hat-cap-back', name: 'CAP, BACKWARDS', price: 700, tag: 'brim behind', kind: 'cap', c: ['#463f52', '#2e2937'], back: true },
    { id: 'hat-bucket', name: 'BUCKET HAT', price: 900, tag: 'all round brim', kind: 'bucket', c: ['#8d9a63', '#5f6b41'] },
    { id: 'hat-helmet', name: 'SKATE HELMET', price: 1100, tag: 'the sensible option', kind: 'helmet', c: ['#e8e2d4', '#a49d8d'] },
    { id: 'hat-helmet-red', name: 'RED HELMET', price: 1400, tag: 'vents and a strap', kind: 'helmet', c: ['#d84a44', '#8f2b2a'] },
    { id: 'hat-visor', name: 'VISOR', price: 1000, tag: 'no crown', kind: 'visor', c: ['#f0d38a', '#b8964f'] },
    { id: 'hat-cap-red', name: 'RED FIVE PANEL', price: 400, tag: '', kind: 'cap', c: ['#b23a35', '#7c2523'] },
    { id: 'hat-cap-cream', name: 'CREAM CAP', price: 400, tag: '', kind: 'cap', c: ['#e8dcc0', '#b8ab8d'] },
    { id: 'hat-cap-back-red', name: 'RED CAP, BACKWARDS', price: 800, tag: 'brim behind', kind: 'cap', c: ['#b23a35', '#7c2523'], back: true },
    { id: 'hat-beanie-grn', name: 'GREEN BEANIE', price: 500, tag: 'cuffed', kind: 'beanie', c: ['#3f6d4a', '#2c4a32'] },
    { id: 'hat-beanie-cream', name: 'CREAM BEANIE', price: 600, tag: '', kind: 'beanie', c: ['#e8dcc0', '#b8ab8d'] },
    { id: 'hat-bucket-blk', name: 'BLACK BUCKET HAT', price: 1000, tag: '', kind: 'bucket', c: ['#3a3542', '#282430'] },
    { id: 'hat-bucket-check', name: 'TAN BUCKET HAT', price: 1100, tag: '', kind: 'bucket', c: ['#d8c08a', '#ab9663'] },
    { id: 'hat-helmet-blue', name: 'BLUE HELMET', price: 1400, tag: 'vents and a strap', kind: 'helmet', c: ['#3d78ab', '#28527a'] },
    { id: 'hat-trucker', name: 'TRUCKER CAP', price: 700, tag: 'mesh back, flat brim', kind: 'cap', c: ['#efe8da', '#b23a35'] },
    { id: 'hat-trucker-blk', name: 'BLACK TRUCKER', price: 800, tag: '', kind: 'cap', c: ['#3a3542', '#8b8797'] },
    { id: 'hat-bandana', name: 'BANDANA', price: 500, tag: 'tied over the top', kind: 'beanie', c: ['#b23a35', '#7c2523'] },
    { id: 'hat-bandana-blue', name: 'BLUE BANDANA', price: 500, tag: '', kind: 'beanie', c: ['#3d4f77', '#2a3752'] },
    { id: 'hat-cap-olive', name: 'OLIVE CAP', price: 500, tag: '', kind: 'cap', c: ['#697548', '#47502f'] },
    { id: 'hat-cap-back-cream', name: 'CREAM CAP, BACKWARDS', price: 900, tag: 'brim behind', kind: 'cap', c: ['#e8dcc0', '#b8ab8d'], back: true },
    { id: 'hat-visor-blk', name: 'BLACK VISOR', price: 1100, tag: 'no crown', kind: 'visor', c: ['#3a3542', '#282430'] },
    { id: 'hat-helmet-blk', name: 'BLACK HELMET', price: 1500, tag: 'vents and a strap', kind: 'helmet', c: ['#33303a', '#5f5c6b'] },
  ],
  face: [
    { id: 'face-none', name: 'NONE', price: 0, tag: '', kind: 'none', c: ['#000', '#000'] },
    { id: 'face-shades', name: 'BLACK SHADES', price: 350, tag: 'wraparound, dark lens', kind: 'shades', c: ['#2a2632', '#6a6478'] },
    { id: 'face-clear', name: 'CLEAR FRAMES', price: 450, tag: 'chunky acetate', kind: 'glasses', c: ['#d8d2c4', '#8f897c'] },
    { id: 'face-amber', name: 'AMBER LENS', price: 700, tag: 'seventies, thin wire', kind: 'wire', c: ['#c98f4e', '#e8bd6e'] },
    { id: 'face-blade', name: 'BLADES', price: 900, tag: 'one wrapped lens', kind: 'blade', c: ['#2f3a4a', '#7fd4e8'] },
    { id: 'face-goggles', name: 'GOGGLES', price: 1200, tag: 'strapped on', kind: 'goggles', c: ['#3c5a78', '#7fb5d8'] },
    { id: 'face-shades-amber', name: 'AMBER SHADES', price: 500, tag: 'warm lens', kind: 'shades', c: ['#8a5c22', '#e8bd6e'] },
    { id: 'face-shades-blue', name: 'BLUE SHADES', price: 600, tag: '', kind: 'shades', c: ['#28527a', '#7fb5d8'] },
    { id: 'face-clear-blk', name: 'BLACK FRAMES', price: 550, tag: 'chunky acetate', kind: 'glasses', c: ['#2a2632', '#5f5a6b'] },
    { id: 'face-clear-tort', name: 'TORTOISESHELL', price: 800, tag: 'flecked brown', kind: 'glasses', c: ['#8a5c2c', '#4a3018'] },
    { id: 'face-wire-silver', name: 'SILVER WIRE', price: 800, tag: 'thin round frames', kind: 'wire', c: ['#cfd8de', '#93a0a8'] },
    { id: 'face-blade-red', name: 'RED BLADES', price: 1000, tag: 'one wrapped lens', kind: 'blade', c: ['#7c2523', '#f0a3bd'] },
    { id: 'face-goggles-blk', name: 'BLACK GOGGLES', price: 1300, tag: 'strapped on', kind: 'goggles', c: ['#2a2632', '#8b8797'] },
  ],

  // --- the base layer -------------------------------------------------------
  // A shirt is always on, and it always hangs LOWER than whatever goes over it,
  // so the hem shows under a jacket.
  shirt: [
    { id: 'tee-red', name: 'RED TEE', price: 0, tag: 'stock', c: ['#ff6b5b', '#d24338', '#94261f'] },
    { id: 'tee-white', name: 'WHITE TEE', price: 150, tag: 'blank', c: ['#efe8da', '#c2bbac', '#8e887b'] },
    { id: 'tee-black', name: 'BLACK TEE', price: 150, tag: 'blank', c: ['#3a3542', '#282430', '#191621'] },
    { id: 'tee-navy', name: 'NAVY TEE', price: 250, tag: '', c: ['#3d4f77', '#2a3752', '#1b2436'] },
    { id: 'tee-cream', name: 'CREAM TEE', price: 250, tag: '', c: ['#f0e2c4', '#cbb894', '#94836a'] },
    { id: 'tee-olive', name: 'OLIVE TEE', price: 350, tag: '', c: ['#8d9a63', '#697548', '#47502f'] },
    { id: 'tee-stripe', name: 'STRIPED TEE', price: 600, tag: 'colour bands', c: ['#efe8da', '#c2bbac', '#3a3542'], stripes: true },
    { id: 'tee-eye', name: 'EYE TEE', price: 700, tag: 'eye in the hand', c: ['#2f2b38', '#211e28', '#161320'], print: 'eye' },
    { id: 'tee-flame', name: 'FLAME TEE', price: 900, tag: 'front print', c: ['#1f1c28', '#161320', '#100e18'], print: 'flame' },
    { id: 'tee-long', name: 'LONG SLEEVE', price: 800, tag: 'sleeves to the wrist', c: ['#5fc0c9', '#3a8d99', '#245f68'], sleeve: true },
    { id: 'tee-long-blk', name: 'BLACK LONG SLEEVE', price: 1000, tag: '', c: ['#3a3542', '#282430', '#191621'], sleeve: true },
    { id: 'tee-skull', name: 'SKULL TEE', price: 1200, tag: '', c: ['#3f4a3a', '#2c352a', '#1c231b'], print: 'skull' },
    { id: 'tee-bolt', name: 'BOLT TEE', price: 1400, tag: 'lightning', c: ['#2e2a36', '#211e28', '#161320'], print: 'bolt' },
    { id: 'tee-star', name: 'STAR TEE', price: 1600, tag: '', c: ['#5fc0c9', '#3a8d99', '#245f68'], print: 'star' },
    { id: 'tee-grey', name: 'HEATHER GREY TEE', price: 250, tag: '', c: ['#b6b2c0', '#8b8797', '#5f5c6b'] },
    { id: 'tee-sand', name: 'SAND TEE', price: 250, tag: '', c: ['#d8c6a0', '#ab9a78', '#736750'] },
    { id: 'tee-rust', name: 'RUST TEE', price: 350, tag: '', c: ['#b5644a', '#8a4632', '#5c2d1f'] },
    { id: 'tee-mustard', name: 'MUSTARD TEE', price: 350, tag: '', c: ['#d8b04a', '#a88430', '#725a1e'] },
    { id: 'tee-forest', name: 'FOREST TEE', price: 350, tag: '', c: ['#3f6d4a', '#2c4a32', '#1c301f'] },
    { id: 'tee-lilac', name: 'LILAC TEE', price: 450, tag: '', c: ['#b9a3d8', '#8d78ab', '#5f4f78'] },
    { id: 'tee-pink', name: 'PINK TEE', price: 450, tag: '', c: ['#f0a3bd', '#c07894', '#8a5163'] },
    { id: 'tee-stripe-navy', name: 'NAVY STRIPES', price: 700, tag: 'wide bands', c: ['#e8e2d4', '#b8b2a4', '#3d4f77'], stripes: true },
    { id: 'tee-stripe-grn', name: 'GREEN STRIPES', price: 700, tag: '', c: ['#f0e2c4', '#c2b596', '#3f6d4a'], stripes: true },
    { id: 'tee-long-wht', name: 'WHITE LONG SLEEVE', price: 900, tag: 'plain, to the wrist', c: ['#efe8da', '#c2bbac', '#8e887b'], sleeve: true },
    { id: 'tee-long-rust', name: 'RUST LONG SLEEVE', price: 1100, tag: '', c: ['#b5644a', '#8a4632', '#5c2d1f'], sleeve: true },
    { id: 'tee-long-stripe', name: 'STRIPED LONG SLEEVE', price: 1400, tag: 'bands and sleeves', c: ['#efe8da', '#c2bbac', '#b5644a'], sleeve: true, stripes: true },
    { id: 'tee-spiral', name: 'SPIRAL TEE', price: 1300, tag: 'hypnotic', c: ['#2e2a36', '#211e28', '#7fd4e8'], print: 'spiral' },
    { id: 'tee-eye-wht', name: 'WHITE EYE TEE', price: 1500, tag: 'eye in the hand, inverted', c: ['#efe8da', '#c2bbac', '#2a2532'], print: 'eye' },
    { id: 'tee-flame-red', name: 'RED FLAME TEE', price: 1700, tag: '', c: ['#7b1c26', '#5a121a', '#3a0c11'], print: 'flame' },
    { id: 'tank-white', name: 'WHITE TANK', price: 300, tag: 'no sleeves at all', c: ['#efe8da', '#c2bbac', '#8e887b'], tank: true },
    { id: 'tank-black', name: 'BLACK TANK', price: 300, tag: '', c: ['#3a3542', '#282430', '#191621'], tank: true },
    { id: 'tank-rib', name: 'RIBBED TANK', price: 600, tag: 'thin straps', c: ['#e8dcc0', '#b8ab8d', '#8a7e63'], tank: true, stripes: true },
    { id: 'tank-red', name: 'RED TANK', price: 500, tag: '', c: ['#b23a35', '#7c2523', '#4d1614'], tank: true },
    { id: 'tee-jersey', name: 'MESH JERSEY', price: 1300, tag: 'numbers on the front', c: ['#3f6d8a', '#2b4d63', '#efe8da'], stripes: true },
    { id: 'tee-jersey-red', name: 'RED JERSEY', price: 1300, tag: '', c: ['#b23a35', '#7c2523', '#efe8da'], stripes: true },
    { id: 'tee-button', name: 'BUTTON-UP', price: 1100, tag: 'collar and a placket', c: ['#a8c3e8', '#7e9dc9', '#3d4f77'], sleeve: true },
    { id: 'tee-button-blk', name: 'BLACK BUTTON-UP', price: 1300, tag: 'tucked, mostly', c: ['#3a3542', '#282430', '#8b8797'], sleeve: true },
    { id: 'tee-tiedye', name: 'TIE DYE', price: 1600, tag: 'spiral, obviously', c: ['#7fd4e8', '#c78ce8', '#ffcf70'], print: 'spiral' },
    { id: 'tee-tiedye-warm', name: 'WARM TIE DYE', price: 1600, tag: '', c: ['#ffcf70', '#ff8a3d', '#c22f36'], print: 'spiral' },
    { id: 'tee-raglan', name: 'RAGLAN', price: 900, tag: 'contrast sleeves', c: ['#efe8da', '#3a3542', '#8b8797'], sleeve: true, stripes: true },
    { id: 'tee-band', name: 'BAND TEE', price: 1500, tag: 'faded print, no idea who', c: ['#2a2532', '#1b1722', '#c2bbac'], print: 'skull' },
  ],

  // --- what goes over it ----------------------------------------------------
  over: [
    { id: 'over-none', name: 'NOTHING', price: 0, tag: 'no jacket over the top', kind: 'none', c: ['#000', '#000', '#000'] },
    { id: 'over-hood-grey', name: 'GREY HOODIE', price: 450, tag: 'oversized', kind: 'hoodie',
      c: ['#b6b2c0', '#8b8797', '#5f5c6b'] },
    { id: 'over-hood-black', name: 'BLACK HOODIE', price: 800, tag: 'boxy fit', kind: 'hoodie',
      c: ['#4a4553', '#332f3c', '#211e28'] },
    { id: 'over-hood-eye', name: 'THIRD EYE HOODIE', price: 1500, tag: 'eye in the hand print', kind: 'hoodie',
      c: ['#3a3346', '#282334', '#191524'], print: 'eye' },
    { id: 'over-hood-flame', name: 'FLAME HOODIE', price: 1700, tag: 'front print', kind: 'hoodie',
      c: ['#2e2a36', '#211e28', '#161320'], print: 'flame' },
    { id: 'over-hood-star', name: 'STAR HOODIE', price: 1900, tag: 'big chest star', kind: 'hoodie',
      c: ['#5fc0c9', '#3a8d99', '#245f68'], print: 'star' },
    { id: 'over-hood-spiral', name: 'SPIRAL HOODIE', price: 2200, tag: 'hypnotic', kind: 'hoodie',
      c: ['#9b7ce0', '#6d55ad', '#453474'], print: 'spiral' },
    { id: 'over-crew', name: 'CREWNECK SWEATER', price: 700, tag: 'no hood', kind: 'sweater',
      c: ['#c9a86a', '#9b7f47', '#6b562e'] },
    { id: 'over-crew-navy', name: 'NAVY SWEATER', price: 900, tag: 'ribbed cuffs', kind: 'sweater',
      c: ['#3d4f77', '#2a3752', '#1b2436'] },
    { id: 'over-crew-grn', name: 'FOREST SWEATER', price: 1100, tag: '', kind: 'sweater',
      c: ['#3f6d4a', '#2a4a32', '#1b3121'] },
    { id: 'over-work', name: 'WORK JACKET', price: 1600, tag: 'canvas, chest pockets', kind: 'work',
      c: ['#c98f4e', '#96682f', '#63451e'] },
    { id: 'over-work-blue', name: 'BLUE CHORE COAT', price: 1900, tag: 'faded workwear', kind: 'work',
      c: ['#5b7fb5', '#3f5d8c', '#2b3f63'] },
    { id: 'over-bomber', name: 'BOMBER JACKET', price: 2400, tag: 'ribbed collar and hem', kind: 'bomber',
      c: ['#4a5340', '#333a2c', '#20251c'] },
    { id: 'over-bomber-blk', name: 'BLACK BOMBER', price: 2800, tag: 'zip all the way up', kind: 'bomber',
      c: ['#33303a', '#232029', '#15131a'] },
    { id: 'over-varsity', name: 'VARSITY JACKET', price: 3400, tag: 'contrast sleeves', kind: 'varsity',
      c: ['#8f3038', '#6b2028', '#efe8da'] },
    { id: 'over-puffer', name: 'PUFFER', price: 3800, tag: 'baffles, far too warm', kind: 'puffer',
      c: ['#c96a4c', '#9a4d35', '#6b3423'] },
    { id: 'over-suit-orange', name: 'ORANGE JUMPSUIT', price: 3000, tag: 'covers the legs too', kind: 'suit',
      c: ['#e8823c', '#b35d24', '#7d3f16'], full: true },
    { id: 'over-suit-blue', name: 'BLUE BOILER SUIT', price: 3200, tag: 'one piece, mechanic', kind: 'suit',
      c: ['#4a6aa5', '#31486f', '#20304b'], full: true },
    { id: 'over-suit-track', name: 'TRACK SUIT', price: 3600, tag: 'stripe down the arm', kind: 'suit',
      c: ['#3a3542', '#282430', '#efe8da'], full: true, stripes: true },
    { id: 'over-hood-cream', name: 'CREAM HOODIE', price: 600, tag: 'washed out', kind: 'hoodie',
      c: ['#e8dcc0', '#b8ab8d', '#8a7e63'] },
    { id: 'over-hood-navy', name: 'NAVY HOODIE', price: 900, tag: '', kind: 'hoodie',
      c: ['#3d4f77', '#2a3752', '#1b2436'] },
    { id: 'over-hood-blue', name: 'BRIGHT BLUE HOODIE', price: 950, tag: 'seen from the far end of the park', kind: 'hoodie',
      c: ['#3d9dff', '#2470c8', '#17457e'] },
    { id: 'over-hood-grn', name: 'FOREST HOODIE', price: 1000, tag: '', kind: 'hoodie',
      c: ['#3f6d4a', '#2c4a32', '#1c301f'] },
    { id: 'over-hood-skull', name: 'SKULL HOODIE', price: 2000, tag: 'big chest skull', kind: 'hoodie',
      c: ['#33303a', '#232029', '#efe8da'], print: 'skull' },
    { id: 'over-hood-bolt', name: 'BOLT HOODIE', price: 2100, tag: 'lightning', kind: 'hoodie',
      c: ['#2e2a36', '#211e28', '#ffe36a'], print: 'bolt' },
    { id: 'over-crew-cream', name: 'CREAM SWEATER', price: 800, tag: 'ribbed hem', kind: 'sweater',
      c: ['#e8dcc0', '#b8ab8d', '#8a7e63'] },
    { id: 'over-crew-rust', name: 'RUST SWEATER', price: 1000, tag: '', kind: 'sweater',
      c: ['#b5644a', '#8a4632', '#5c2d1f'] },
    { id: 'over-crew-stripe', name: 'STRIPED SWEATER', price: 1500, tag: 'two bands', kind: 'sweater',
      c: ['#d8c6a0', '#ab9a78', '#3d4f77'], stripes: true },
    { id: 'over-work-blk', name: 'BLACK CHORE COAT', price: 2000, tag: 'canvas, four pockets', kind: 'work',
      c: ['#3a3542', '#282430', '#191621'] },
    { id: 'over-work-tan', name: 'TAN WORK JACKET', price: 2100, tag: 'faded duck canvas', kind: 'work',
      c: ['#d8c08a', '#ab9663', '#736440'] },
    { id: 'over-denim', name: 'DENIM JACKET', price: 2200, tag: 'buttons and chest pockets', kind: 'work',
      c: ['#6d92cf', '#4a6aa5', '#31486f'] },
    { id: 'over-denim-wash', name: 'WASHED DENIM JACKET', price: 2500, tag: 'faded to nearly white', kind: 'work',
      c: ['#a8c3e8', '#7e9dc9', '#566f96'] },
    { id: 'over-bomber-olive', name: 'OLIVE BOMBER', price: 2600, tag: 'ribbed collar and hem', kind: 'bomber',
      c: ['#697548', '#47502f', '#8d9a63'] },
    { id: 'over-bomber-red', name: 'RED BOMBER', price: 2900, tag: '', kind: 'bomber',
      c: ['#b23a35', '#7c2523', '#e8dcc0'] },
    { id: 'over-varsity-blue', name: 'BLUE VARSITY', price: 3600, tag: 'contrast sleeves', kind: 'varsity',
      c: ['#3d4f77', '#2a3752', '#e8dcc0'] },
    { id: 'over-puffer-blk', name: 'BLACK PUFFER', price: 4000, tag: 'baffles all the way down', kind: 'puffer',
      c: ['#33303a', '#232029', '#4d4859'] },
    { id: 'over-puffer-cream', name: 'CREAM PUFFER', price: 4200, tag: 'enormous', kind: 'puffer',
      c: ['#e8dcc0', '#b8ab8d', '#cfc2a4'] },
    { id: 'over-suit-green', name: 'GREEN BOILER SUIT', price: 3400, tag: 'one piece', kind: 'suit',
      c: ['#4f7d33', '#345121', '#8ada6a'], full: true },
    { id: 'over-suit-red', name: 'RED TRACK SUIT', price: 3800, tag: 'stripe down the arm', kind: 'suit',
      c: ['#b23a35', '#7c2523', '#efe8da'], full: true, stripes: true },
    { id: 'over-vest-black', name: 'PUFFER VEST', price: 2200, tag: 'no sleeves, all body', kind: 'vest',
      c: ['#33303a', '#232029', '#4d4859'] },
    { id: 'over-vest-olive', name: 'OLIVE GILET', price: 2300, tag: 'quilted', kind: 'vest',
      c: ['#697548', '#47502f', '#8d9a63'] },
    { id: 'over-vest-orange', name: 'HI-VIS VEST', price: 1400, tag: 'visible from space', kind: 'vest',
      c: ['#ff8a3d', '#c2521f', '#efe8da'] },
    { id: 'over-flannel-red', name: 'RED FLANNEL', price: 1500, tag: 'worn open over a tee', kind: 'flannel',
      c: ['#b23a35', '#7c2523', '#2a2532'] },
    { id: 'over-flannel-blue', name: 'BLUE FLANNEL', price: 1500, tag: 'checked', kind: 'flannel',
      c: ['#3d4f77', '#2a3752', '#e8dcc0'] },
    { id: 'over-flannel-grn', name: 'GREEN FLANNEL', price: 1600, tag: '', kind: 'flannel',
      c: ['#3f6d4a', '#2c4a32', '#e8dcc0'] },
    { id: 'over-leather', name: 'LEATHER JACKET', price: 3200, tag: 'lapels, off-centre zip', kind: 'leather',
      c: ['#2f2b38', '#1e1b26', '#6a6478'] },
    { id: 'over-leather-brown', name: 'BROWN LEATHER', price: 3400, tag: 'worn in', kind: 'leather',
      c: ['#7d552a', '#54391b', '#a8763f'] },
    { id: 'over-coach', name: 'COACH JACKET', price: 2000, tag: 'snaps and a lined collar', kind: 'coach',
      c: ['#3a3542', '#282430', '#efe8da'] },
    { id: 'over-coach-navy', name: 'NAVY COACH JACKET', price: 2100, tag: '', kind: 'coach',
      c: ['#3d4f77', '#2a3752', '#efe8da'] },
    { id: 'over-windbreaker', name: 'WINDBREAKER', price: 1800, tag: 'shiny, and it rustles', kind: 'coach',
      c: ['#5fc0c9', '#3a8d99', '#ffcf70'] },
    { id: 'over-cardigan', name: 'CARDIGAN', price: 1700, tag: 'buttons, worn open', kind: 'cardigan',
      c: ['#8a7e63', '#5f5644', '#d8c08a'] },
    { id: 'over-cardigan-grey', name: 'GREY CARDIGAN', price: 1800, tag: '', kind: 'cardigan',
      c: ['#8b8797', '#5f5c6b', '#c2bec9'] },
    { id: 'over-hood-zip', name: 'ZIP HOODIE', price: 1200, tag: 'zipped to the chin', kind: 'hoodie',
      c: ['#4b4756', '#35323e', '#8b8797'] },
    { id: 'over-anorak', name: 'ANORAK', price: 2600, tag: 'one big pocket', kind: 'work',
      c: ['#d8683f', '#a8482a', '#e8dcc0'] },
  ],

  // --- legs -----------------------------------------------------------------
  // fit drives how the leg is DRAWN. skinny is a tight taper with the legs
  // close together; slim has daylight at the knee; baggy is wide and stacks
  // over the shoe; wide is wider again.
  // Two shapes only, and the ladder sits one rung lower than it used to: SLIM
  // is a thin leg with daylight between the knees, BAGGY is the wider straight
  // leg. The old fat fits drew as two blocks of colour, so they are gone --
  // cargos and carpenters are baggy now, not wider still.
  legs: [
    { id: 'legs-slim', name: 'SLIM DENIM', price: 0, tag: 'thin leg, gap at the knee, stock',
      c: ['#6d92cf', '#4a6aa5', '#31486f'], fit: 'slim' },
    { id: 'legs-slim-blk', name: 'BLACK SLIMS', price: 300, tag: 'straight and narrow',
      c: ['#4b4756', '#35323e', '#232028'], fit: 'slim' },
    { id: 'legs-slim-wash', name: 'LIGHT WASH SLIMS', price: 600, tag: 'faded, thin leg',
      c: ['#a8c3e8', '#7e9dc9', '#566f96'], fit: 'slim' },
    { id: 'legs-cord', name: 'BROWN CORDS', price: 1400, tag: 'wide wale, slim leg',
      c: ['#a8763f', '#7d552a', '#54391b'], fit: 'slim' },
    { id: 'legs-sweat-navy', name: 'NAVY JOGGERS', price: 1200, tag: 'slim, cuffed',
      c: ['#3d4f77', '#2a3752', '#1b2436'], fit: 'slim', sweat: true },
    { id: 'legs-shorts', name: 'SHORTS', price: 600, tag: 'above the knee',
      c: ['#d8683f', '#a8482a', '#75301b'], fit: 'slim', short: 0.38 },

    { id: 'legs-baggy', name: 'BAGGY DENIM', price: 800, tag: 'straight leg, sits over the shoe',
      c: ['#6d92cf', '#4a6aa5', '#31486f'], fit: 'baggy' },
    { id: 'legs-baggy-wash', name: 'LIGHT WASH BAGGIES', price: 1100, tag: 'faded',
      c: ['#a8c3e8', '#7e9dc9', '#566f96'], fit: 'baggy' },
    { id: 'legs-black', name: 'BLACK BAGGIES', price: 1300, tag: 'the safe option',
      c: ['#4b4756', '#35323e', '#232028'], fit: 'baggy' },
    { id: 'legs-carpenter', name: 'CARPENTER PANTS', price: 1500, tag: 'hammer loop',
      c: ['#d8c08a', '#ab9663', '#736440'], fit: 'baggy', loop: true },
    { id: 'legs-cargo', name: 'OLIVE CARGOS', price: 1900, tag: 'pockets everywhere',
      c: ['#8d9a63', '#697548', '#47502f'], fit: 'baggy', loop: true },
    { id: 'legs-cargo-blk', name: 'BLACK CARGOS', price: 2200, tag: 'pockets, in black',
      c: ['#4b4756', '#35323e', '#232028'], fit: 'baggy', loop: true },
    { id: 'legs-sweat-grey', name: 'GREY SWEATPANTS', price: 700, tag: 'elastic cuff',
      c: ['#b6b2c0', '#8b8797', '#5f5c6b'], fit: 'baggy', sweat: true },
    { id: 'legs-sweat-blk', name: 'BLACK SWEATPANTS', price: 900, tag: 'drawstring',
      c: ['#3a3542', '#282430', '#191621'], fit: 'baggy', sweat: true },
    { id: 'legs-track', name: 'TRACK PANTS', price: 1600, tag: 'stripe down the side',
      c: ['#33303a', '#232029', '#efe8da'], fit: 'baggy', sweat: true, stripe: true },
    { id: 'legs-jorts', name: 'JORTS', price: 700, tag: 'below the knee',
      c: ['#7fa0d8', '#5a79ad', '#3d5578'], fit: 'baggy', short: 0.55 },
    { id: 'legs-jorts-black', name: 'BLACK JORTS', price: 1000, tag: 'cut off',
      c: ['#4b4756', '#35323e', '#232028'], fit: 'baggy', short: 0.55 },
    { id: 'legs-shorts-cargo', name: 'CARGO SHORTS', price: 1500, tag: 'pockets, short',
      c: ['#8d9a63', '#697548', '#47502f'], fit: 'baggy', short: 0.42, loop: true },
    { id: 'legs-slim-grey', name: 'GREY SLIMS', price: 500, tag: 'washed grey', fit: 'slim',
      c: ['#8b8797', '#5f5c6b', '#403d4a'] },
    { id: 'legs-slim-cream', name: 'CREAM SLIMS', price: 700, tag: 'off white, thin leg', fit: 'slim',
      c: ['#e8dcc0', '#b8ab8d', '#8a7e63'] },
    { id: 'legs-slim-olive', name: 'OLIVE SLIMS', price: 800, tag: '', fit: 'slim',
      c: ['#8d9a63', '#697548', '#47502f'] },
    { id: 'legs-chino', name: 'TAN CHINOS', price: 900, tag: 'pressed, slim', fit: 'slim',
      c: ['#d8c08a', '#ab9663', '#736440'] },
    { id: 'legs-cord-slim', name: 'RUST CORDS', price: 1200, tag: 'wide wale, thin leg', fit: 'slim',
      c: ['#b5644a', '#8a4632', '#5c2d1f'] },
    { id: 'legs-baggy-blk-wash', name: 'FADED BLACK BAGGIES', price: 1200, tag: 'washed out', fit: 'baggy',
      c: ['#6a6470', '#494352', '#2e2937'] },
    { id: 'legs-baggy-indigo', name: 'RAW INDIGO BAGGIES', price: 1600, tag: 'dark and stiff', fit: 'baggy',
      c: ['#3d4f77', '#2a3752', '#1b2436'] },
    { id: 'legs-baggy-cream', name: 'CREAM BAGGIES', price: 1700, tag: 'will not stay clean', fit: 'baggy',
      c: ['#e8dcc0', '#b8ab8d', '#8a7e63'] },
    { id: 'legs-carpenter-blk', name: 'BLACK CARPENTERS', price: 1800, tag: 'hammer loop', fit: 'baggy', loop: true,
      c: ['#3a3542', '#282430', '#191621'] },
    { id: 'legs-cargo-tan', name: 'TAN CARGOS', price: 2000, tag: 'pockets everywhere', fit: 'baggy', loop: true,
      c: ['#d8c08a', '#ab9663', '#736440'] },
    { id: 'legs-sweat-olive', name: 'OLIVE SWEATPANTS', price: 1000, tag: 'elastic cuff', fit: 'baggy', sweat: true,
      c: ['#8d9a63', '#697548', '#47502f'] },
    { id: 'legs-sweat-cream', name: 'CREAM SWEATPANTS', price: 1100, tag: 'drawstring', fit: 'baggy', sweat: true,
      c: ['#e8dcc0', '#b8ab8d', '#8a7e63'] },
    { id: 'legs-jogger-blk', name: 'BLACK JOGGERS', price: 1300, tag: 'slim, cuffed', fit: 'slim', sweat: true,
      c: ['#3a3542', '#282430', '#191621'] },
    { id: 'legs-track-red', name: 'RED TRACK PANTS', price: 1800, tag: 'stripe down the side', fit: 'baggy', sweat: true, stripe: true,
      c: ['#b23a35', '#7c2523', '#efe8da'] },
    { id: 'legs-track-blue', name: 'BLUE TRACK PANTS', price: 1800, tag: 'stripe down the side', fit: 'baggy', sweat: true, stripe: true,
      c: ['#3d4f77', '#2a3752', '#efe8da'] },
    { id: 'legs-jorts-wash', name: 'LIGHT WASH JORTS', price: 900, tag: 'below the knee', fit: 'baggy', short: 0.55,
      c: ['#a8c3e8', '#7e9dc9', '#566f96'] },
    { id: 'legs-shorts-blk', name: 'BLACK SHORTS', price: 700, tag: 'above the knee', fit: 'slim', short: 0.38,
      c: ['#3a3542', '#282430', '#191621'] },
    { id: 'legs-shorts-cream', name: 'CREAM SHORTS', price: 800, tag: '', fit: 'slim', short: 0.4,
      c: ['#e8dcc0', '#b8ab8d', '#8a7e63'] },
    { id: 'legs-parachute', name: 'PARACHUTE PANTS', price: 2400, tag: 'straps and buckles everywhere', fit: 'baggy', loop: true, sweat: true,
      c: ['#6b7355', '#4a5139', '#8d9a63'] },
    { id: 'legs-painter', name: 'PAINTER PANTS', price: 1600, tag: 'white, loop on the leg', fit: 'baggy', loop: true,
      c: ['#e8e2d4', '#b8b2a4', '#8a8578'] },
    { id: 'legs-dickies', name: 'WORK PANTS', price: 1400, tag: 'creased, hard wearing', fit: 'baggy',
      c: ['#33303a', '#232029', '#5f5c6b'] },
    { id: 'legs-dickies-tan', name: 'TAN WORK PANTS', price: 1400, tag: '', fit: 'baggy',
      c: ['#c9ad7a', '#9b8256', '#6b5a3a'] },
    { id: 'legs-cord-wide', name: 'WIDE CORDS', price: 1700, tag: 'wide wale, wide leg', fit: 'baggy',
      c: ['#8a6a3c', '#5f4726', '#3d2d16'] },
    { id: 'legs-plaid', name: 'PLAID TROUSERS', price: 2000, tag: 'checked, and loud', fit: 'baggy', stripe: true,
      c: ['#7c2523', '#4d1614', '#e8dcc0'] },
    { id: 'legs-leggings', name: 'LEGGINGS', price: 800, tag: 'nothing to catch on the trucks', fit: 'slim',
      c: ['#2a2532', '#1b1722', '#4b4756'] },
    { id: 'legs-cord-shorts', name: 'CORDUROY SHORTS', price: 900, tag: 'above the knee', fit: 'slim', short: 0.4,
      c: ['#a8763f', '#7d552a', '#54391b'] },
    { id: 'legs-board-shorts', name: 'BOARD SHORTS', price: 1000, tag: 'straight off the beach', fit: 'baggy', short: 0.5, stripe: true,
      c: ['#3fa8e8', '#2b7ab0', '#efe8da'] },
  ],
  socks: [
    { id: 'socks-none', name: 'NO SOCKS', price: 0, tag: 'brave', kind: 'none', c: ['#000', '#000'] },
    { id: 'socks-white', name: 'WHITE CREW', price: 150, tag: 'just over the shoe', kind: 'crew', c: ['#f2ede0', '#c4beae'] },
    { id: 'socks-black', name: 'BLACK CREW', price: 150, tag: '', kind: 'crew', c: ['#3a3542', '#26222d'] },
    { id: 'socks-stripe', name: 'STRIPED TUBE', price: 500, tag: 'two bars, pulled up', kind: 'tall', c: ['#f2ede0', '#d24338'], stripe: true },
    { id: 'socks-tall-blk', name: 'TALL BLACK', price: 650, tag: 'over the calf', kind: 'tall', c: ['#3a3542', '#26222d'] },
    { id: 'socks-cream', name: 'CREAM CREW', price: 200, tag: '', kind: 'crew', c: ['#e8dcc0', '#b8ab8d'] },
    { id: 'socks-navy', name: 'NAVY CREW', price: 200, tag: '', kind: 'crew', c: ['#3d4f77', '#2a3752'] },
    { id: 'socks-tall-wht', name: 'TALL WHITE', price: 550, tag: 'over the calf', kind: 'tall', c: ['#f2ede0', '#c4beae'] },
    { id: 'socks-stripe-blue', name: 'BLUE STRIPED TUBE', price: 600, tag: 'two bars', kind: 'tall', c: ['#f2ede0', '#3d4f77'], stripe: true },
    { id: 'socks-stripe-grn', name: 'GREEN STRIPED TUBE', price: 600, tag: '', kind: 'tall', c: ['#f2ede0', '#3f6d4a'], stripe: true },
    { id: 'socks-grey', name: 'GREY CREW', price: 200, tag: '', kind: 'crew', c: ['#b6b2c0', '#8b8797'] },
    { id: 'socks-tall-navy', name: 'TALL NAVY', price: 600, tag: 'over the calf', kind: 'tall', c: ['#3d4f77', '#2a3752'] },
    { id: 'socks-stripe-red', name: 'RED STRIPED TUBE', price: 600, tag: 'two bars', kind: 'tall', c: ['#f2ede0', '#b23a35'], stripe: true },
    { id: 'socks-stripe-yel', name: 'GOLD STRIPED TUBE', price: 650, tag: '', kind: 'tall', c: ['#f2ede0', '#d8b04a'], stripe: true },
  ],
  shoes: [
    { id: 'shoe-stock', name: 'CANVAS LOW', price: 0, tag: 'stock', c: ['#6f675c', '#4e4740'], sole: '#f6f2e6' },
    { id: 'shoe-check', name: 'CHECKER SLIP-ONS', price: 500, tag: 'the classic', c: ['#2a2532', '#1b1722'], sole: '#f6f2e6', checker: true },
    { id: 'shoe-check-red', name: 'RED CHECKER SLIP-ONS', price: 800, tag: '', c: ['#b23a35', '#7c2523'], sole: '#f6f2e6', checker: true },
    { id: 'shoe-suede', name: 'NAVY SUEDE', price: 800, tag: 'padded collar', c: ['#3d4f77', '#2a3752'], sole: '#f6f2e6' },
    { id: 'shoe-suede-grn', name: 'GREEN SUEDE', price: 1000, tag: '', c: ['#3f6d4a', '#2a4a32'], sole: '#f6f2e6' },
    { id: 'shoe-red', name: 'RED CANVAS HI', price: 1100, tag: 'over the ankle', c: ['#b23a35', '#7c2523'], sole: '#f6f2e6', hi: true },
    { id: 'shoe-blk-hi', name: 'BLACK HI-TOP', price: 1300, tag: '', c: ['#2f2b38', '#1e1b26'], sole: '#f6f2e6', hi: true },
    { id: 'shoe-white', name: 'ALL WHITE', price: 1500, tag: 'will not stay white', c: ['#eae5d8', '#bab4a4'], sole: '#f6f2e6' },
    { id: 'shoe-gum', name: 'GUM SOLE SUEDE', price: 1900, tag: 'tan sole', c: ['#5c5346', '#403a31'], sole: '#c98f4e' },
    { id: 'shoe-gum-blue', name: 'BLUE GUM SOLE', price: 2100, tag: '', c: ['#41567d', '#2c3b57'], sole: '#c98f4e' },
    { id: 'shoe-chunky', name: 'CHUNKY SKATE SHOE', price: 2400, tag: 'a lot of shoe', c: ['#2f3a4a', '#1f2833'], sole: '#efe8da', hi: true, chunky: true },
    { id: 'shoe-chunky-wht', name: 'CHUNKY WHITE', price: 2800, tag: 'even more shoe', c: ['#eae5d8', '#b8b2a2'], sole: '#efe8da', hi: true, chunky: true },
    { id: 'shoe-orange', name: 'ORANGE SUEDE', price: 2600, tag: 'loud', c: ['#d8683f', '#a8482a'], sole: '#f6f2e6' },
    { id: 'shoe-cream-hi', name: 'CREAM HI-TOP', price: 3000, tag: 'gum sole, high', c: ['#e8dcc0', '#b8ab8d'], sole: '#c98f4e', hi: true },
    { id: 'shoe-flip', name: 'FLIP FLOPS', price: 300, tag: 'a genuinely bad idea', c: ['#3f6d5a', '#2c5142'], sole: '#d8cdb8', flip: true },
    { id: 'shoe-barefoot', name: 'BAREFOOT', price: 800, tag: 'worse', c: [null, null], sole: null, bare: true },
    { id: 'shoe-navy-low', name: 'NAVY CANVAS LOW', price: 400, tag: '', c: ['#3d4f77', '#2a3752'], sole: '#f6f2e6' },
    { id: 'shoe-olive-low', name: 'OLIVE CANVAS LOW', price: 400, tag: '', c: ['#697548', '#47502f'], sole: '#f6f2e6' },
    { id: 'shoe-cream-low', name: 'CREAM CANVAS LOW', price: 600, tag: '', c: ['#e8dcc0', '#b8ab8d'], sole: '#f6f2e6' },
    { id: 'shoe-check-blue', name: 'BLUE CHECKER SLIP-ONS', price: 900, tag: '', c: ['#3d4f77', '#2a3752'], sole: '#f6f2e6', checker: true },
    { id: 'shoe-check-grn', name: 'GREEN CHECKER SLIP-ONS', price: 900, tag: '', c: ['#3f6d4a', '#2c4a32'], sole: '#f6f2e6', checker: true },
    { id: 'shoe-suede-rust', name: 'RUST SUEDE', price: 1200, tag: 'padded collar', c: ['#b5644a', '#8a4632'], sole: '#f6f2e6' },
    { id: 'shoe-suede-grey', name: 'GREY SUEDE', price: 1200, tag: '', c: ['#8b8797', '#5f5c6b'], sole: '#f6f2e6' },
    { id: 'shoe-gum-blk', name: 'BLACK GUM SOLE', price: 2000, tag: 'tan sole', c: ['#2f2b38', '#1e1b26'], sole: '#c98f4e' },
    { id: 'shoe-gum-olive', name: 'OLIVE GUM SOLE', price: 2000, tag: '', c: ['#697548', '#47502f'], sole: '#c98f4e' },
    { id: 'shoe-hi-navy', name: 'NAVY HI-TOP', price: 1600, tag: 'over the ankle', c: ['#3d4f77', '#2a3752'], sole: '#f6f2e6', hi: true },
    { id: 'shoe-hi-cream', name: 'CREAM HI-TOP', price: 1800, tag: '', c: ['#e8dcc0', '#b8ab8d'], sole: '#f6f2e6', hi: true },
    { id: 'shoe-chunky-red', name: 'CHUNKY RED', price: 3000, tag: 'a lot of shoe', c: ['#b23a35', '#7c2523'], sole: '#efe8da', hi: true, chunky: true },
    { id: 'shoe-chunky-tan', name: 'CHUNKY TAN', price: 3200, tag: 'even more shoe', c: ['#d8c08a', '#ab9663'], sole: '#efe8da', hi: true, chunky: true },
    { id: 'shoe-yellow', name: 'YELLOW SUEDE', price: 2800, tag: 'very loud', c: ['#d8b04a', '#a88430'], sole: '#f6f2e6' },
    { id: 'shoe-purple', name: 'PURPLE SUEDE', price: 2800, tag: '', c: ['#8a63c9', '#5c3f8f'], sole: '#f6f2e6' },
    { id: 'shoe-flip-blk', name: 'BLACK FLIP FLOPS', price: 400, tag: 'still a bad idea', c: ['#3a3542', '#282430'], sole: '#8b8797', flip: true },
    { id: 'shoe-boot', name: 'WORK BOOTS', price: 2400, tag: 'a genuinely odd choice', c: ['#8a5c2c', '#5c3c18'], sole: '#3a3542', hi: true, chunky: true },
    { id: 'shoe-boot-blk', name: 'BLACK BOOTS', price: 2600, tag: '', c: ['#33303a', '#232029'], sole: '#1b1722', hi: true, chunky: true },
    { id: 'shoe-pink', name: 'PINK SUEDE', price: 2600, tag: '', c: ['#f083b5', '#b4507f'], sole: '#f6f2e6' },
    { id: 'shoe-teal', name: 'TEAL CANVAS', price: 1400, tag: '', c: ['#3a8d99', '#245f68'], sole: '#f6f2e6' },
    { id: 'shoe-check-yel', name: 'YELLOW CHECKER SLIP-ONS', price: 1000, tag: '', c: ['#d8b04a', '#a88430'], sole: '#f6f2e6', checker: true },
    { id: 'shoe-hi-red', name: 'RED HI-TOP', price: 1700, tag: 'over the ankle', c: ['#b23a35', '#7c2523'], sole: '#f6f2e6', hi: true },
    { id: 'shoe-hi-grn', name: 'GREEN HI-TOP', price: 1700, tag: '', c: ['#3f6d4a', '#2c4a32'], sole: '#f6f2e6', hi: true },
    { id: 'shoe-gum-cream', name: 'CREAM GUM SOLE', price: 2200, tag: 'tan sole', c: ['#e8dcc0', '#b8ab8d'], sole: '#c98f4e' },
    { id: 'shoe-chunky-blue', name: 'CHUNKY BLUE', price: 3100, tag: 'a lot of shoe', c: ['#3d4f77', '#2a3752'], sole: '#efe8da', hi: true, chunky: true },
    { id: 'shoe-slide', name: 'SLIDES', price: 500, tag: 'with socks, obviously', c: ['#3a3542', '#282430'], sole: '#8b8797', flip: true },
  ],

  // --- the board ------------------------------------------------------------
  deck: [
    { id: 'deck-blank', name: 'BLANK MAPLE', price: 0, tag: 'stock', art: ['#e6c68e', '#c09a5e', '#8d6c36'], ply: ['#f0d38a', '#c9a45c', '#8f6f36'], graphic: 'plain' },
    { id: 'deck-hotrod', name: 'HOT ROD', price: 350, tag: 'orange stripe', art: ['#ff8a3d', '#d1552a', '#8f3218'], ply: ['#ff8a3d', '#c2521f', '#7d3212'], graphic: 'stripe' },
    { id: 'deck-check', name: 'CHECKERBOARD', price: 700, tag: 'black and bone', art: ['#f4e3c6', '#2a2532', '#1b1722'], ply: ['#3a3444', '#282334', '#181423'], graphic: 'checker' },
    { id: 'deck-split', name: 'SPLIT DIP', price: 1000, tag: 'teal over cream', art: ['#7fd4e8', '#3f97b2', '#f4e3c6'], ply: ['#7fd4e8', '#3f97b2', '#245f74'], graphic: 'split' },
    { id: 'deck-flame', name: 'FLAME', price: 1400, tag: 'licks down the middle', art: ['#ffd23c', '#ff5b2e', '#7b1c26'], ply: ['#c22f36', '#8f1f26', '#5a1218'], graphic: 'flame' },
    { id: 'deck-eye', name: 'THIRD EYE', price: 1800, tag: 'eye in the hand', art: ['#e8d9a8', '#6d55ad', '#2c2340'], ply: ['#6d55ad', '#4a3878', '#2c2340'], graphic: 'eye' },
    { id: 'deck-bolt', name: 'LIGHTNING', price: 2100, tag: 'bolt down the belly', art: ['#ffe36a', '#3a3346', '#191524'], ply: ['#ffe36a', '#c2a83c', '#7d6a1c'], graphic: 'bolt' },
    { id: 'deck-void', name: 'MIDNIGHT FADE', price: 2400, tag: 'purple fade', art: ['#8f7ce8', '#5a4fd6', '#2f2a7a'], ply: ['#5a4fd6', '#3d359c', '#241f62'], graphic: 'split' },
    { id: 'deck-check-red', name: 'RED CHECKERBOARD', price: 900, tag: 'red and bone', art: ['#f4e3c6', '#b23a35', '#7c2523'], ply: ['#b23a35', '#7c2523', '#4d1614'], graphic: 'checker' },
    { id: 'deck-stripe-grn', name: 'GREEN STRIPE', price: 500, tag: 'one band down the belly', art: ['#8ada6a', '#4f8f3c', '#2b5723'], ply: ['#4f8f3c', '#38661f', '#20400f'], graphic: 'stripe' },
    { id: 'deck-split-rust', name: 'RUST DIP', price: 1200, tag: 'dipped half and half', art: ['#b5644a', '#8a4632', '#e8dcc0'], ply: ['#b5644a', '#8a4632', '#5c2d1f'], graphic: 'split' },
    { id: 'deck-skull', name: 'SKULL', price: 2000, tag: 'across the middle', art: ['#efe8da', '#8b8797', '#2a2532'], ply: ['#3a3444', '#282334', '#181423'], graphic: 'eye' },
    { id: 'deck-flame-blue', name: 'COLD FLAME', price: 2200, tag: 'licks, in blue', art: ['#cdf3ff', '#3f97b2', '#1f5b74'], ply: ['#3f97b2', '#2b6b80', '#194352'], graphic: 'flame' },
    { id: 'deck-bolt-pink', name: 'PINK LIGHTNING', price: 2300, tag: '', art: ['#f083b5', '#3a3346', '#191524'], ply: ['#f083b5', '#b4507f', '#7a2f5c'], graphic: 'bolt' },
    { id: 'deck-custom', name: 'CUSTOM PRINT', price: 3000, tag: 'paint it yourself, edge included',
      art: ['#e6c68e', '#c09a5e', '#8d6c36'], graphic: 'custom' },
  ],
  grip: [
    { id: 'grip-black', name: 'BLACK GRIP', price: 0, tag: 'stock', grip: ['#3d3646', '#2a2532'] },
    { id: 'grip-clear', name: 'CLEAR GRIP', price: 250, tag: 'lets the ply show', grip: ['#a08c6a', '#6f5f45'] },
    { id: 'grip-red', name: 'RED GRIP', price: 450, tag: 'loud', grip: ['#8f2f38', '#5e1e26'] },
    { id: 'grip-white', name: 'BONE GRIP', price: 700, tag: 'gets filthy', grip: ['#d8cdb8', '#a2977f'] },
    { id: 'grip-blue', name: 'BLUE GRIP', price: 700, tag: '', grip: ['#33547d', '#213652'] },
    { id: 'grip-green', name: 'ACID GRIP', price: 900, tag: '', grip: ['#4f7d33', '#345121'] },
    { id: 'grip-purple', name: 'PURPLE GRIP', price: 700, tag: '', grip: ['#5c3f8f', '#3d2a60'] },
    { id: 'grip-pink', name: 'PINK GRIP', price: 900, tag: 'very loud', grip: ['#b4507f', '#7a2f5c'] },
    { id: 'grip-tan', name: 'TAN GRIP', price: 600, tag: '', grip: ['#8a6a3c', '#5c4526'] },
    { id: 'grip-custom', name: 'CUSTOM GRIP', price: 1200, tag: 'pick your own two colours',
      grip: ['#3d3646', '#2a2532'], custom: true },
  ],
  wheels: [
    { id: 'wheel-bone', name: 'BONE 52MM', price: 0, tag: 'stock',
      wheels: ['#fff4d8', '#d6c49e', '#93816a'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-black', name: 'BLACKOUT 54MM', price: 300, tag: 'quiet',
      wheels: ['#6a6470', '#494352', '#2e2937'], trucks: ['#8e8a97', '#605c6b', '#3b3846'] },
    { id: 'wheel-cyan', name: 'ICE 53MM', price: 600, tag: 'bright',
      wheels: ['#cdf3ff', '#8fd0e4', '#5b93a8'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-red', name: 'EMBER 55MM', price: 1000, tag: 'soft, fast',
      wheels: ['#ffb0a0', '#d8695c', '#8f3830'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-green', name: 'LIME 52MM', price: 1200, tag: '',
      wheels: ['#d6f2a8', '#9ac95f', '#638a33'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-purple', name: 'GRAPE 54MM', price: 1400, tag: '',
      wheels: ['#d6c0f2', '#9b7ce0', '#6045a0'], trucks: ['#8e8a97', '#605c6b', '#3b3846'] },
    { id: 'wheel-gold', name: 'BRASS 55MM', price: 1600, tag: 'polished trucks',
      wheels: ['#ffe6a8', '#d9b45e', '#9a7a2e'], trucks: ['#ffd98a', '#c8a04e', '#7d6224'] },
    { id: 'wheel-pink', name: 'BUBBLEGUM 53MM', price: 1800, tag: '',
      wheels: ['#ffd0e2', '#f083b5', '#b4507f'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-raw', name: 'RAW TRUCKS 56MM', price: 2400, tag: 'unpolished, big',
      wheels: ['#efe8da', '#c2bbac', '#8e887b'], trucks: ['#e6eef2', '#aebac2', '#78868f'] },
    { id: 'wheel-orange', name: 'SUNSET 54MM', price: 900, tag: '',
      wheels: ['#ffd0a8', '#e0955c', '#a35f2e'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-teal', name: 'SEAFOAM 53MM', price: 1100, tag: '',
      wheels: ['#c0f2e6', '#7ec9b5', '#458a76'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'] },
    { id: 'wheel-yellow', name: 'HIGHLIGHTER 52MM', price: 1300, tag: 'hard to miss',
      wheels: ['#fbff9e', '#d8dc4e', '#8f9320'], trucks: ['#8e8a97', '#605c6b', '#3b3846'] },
    { id: 'wheel-clear', name: 'CLEAR 54MM', price: 2000, tag: 'nearly see-through',
      wheels: ['#eef6fa', '#c6d6de', '#93a6b0'], trucks: ['#e6eef2', '#aebac2', '#78868f'] },
    { id: 'wheel-gold-blk', name: 'BLACK AND BRASS 56MM', price: 2600, tag: 'polished trucks, big',
      wheels: ['#4d4859', '#33303a', '#211f27'], trucks: ['#ffd98a', '#c8a04e', '#7d6224'] },
    { id: 'wheel-custom', name: 'CUSTOM WHEELS', price: 2600, tag: 'your colours, wheels and trucks',
      wheels: ['#fff4d8', '#d6c49e', '#93816a'], trucks: ['#cfd8de', '#93a0a8', '#5f6a72'], custom: true },
  ],
};

// The palette every custom design paints from.
export const PRINT_COLORS = [
  null,
  '#ffffff', '#f4e3c6', '#e6c68e', '#c98f4e', '#8d6c36', '#54391b',
  '#ffe36a', '#ffd23c', '#ffa03c', '#ff8a3d', '#ff5b2e', '#c22f36', '#7b1c26',
  '#ffd0e2', '#f083b5', '#b4507f', '#7a2f5c',
  '#d6c0f2', '#9b7ce0', '#5a4fd6', '#2f2a7a',
  '#cdf3ff', '#7fd4e8', '#3f97b2', '#1f5b74',
  '#d6f2a8', '#8ada6a', '#4f8f3c', '#2b5723',
  '#d8d2c4', '#9aa7ae', '#5f6a72', '#3a3542', '#2a2532', '#12101a',
  '#ffb3c9', '#e0679a', '#a8336a', '#f7a35c', '#c96f2c', '#8a4a14',
  '#b8e6a0', '#6fbf72', '#2f7a4a', '#a0e8e0', '#4fb5b5', '#1f6b73',
  '#c4b0f7', '#7f63d8', '#4a2f9b', '#e8e0b0', '#b5a56a', '#6b5f2e',
];
// The board's underside, in cells. Wide and shallow because a deck is: the
// graphic runs the length of it and there is not much width to play with.
export const PRINT_COLS = 40;
export const PRINT_ROWS = 16;

// A wheel face is a disc a few pixels across, so its grid is small and square
// and gets clipped to the circle when it is drawn.
export const WHEEL_COLS = 13;
export const WHEEL_ROWS = 13;

// Grid size per paintable thing.
export function gridSize(kind) {
  return kind === 'wheels'
    ? { cols: WHEEL_COLS, rows: WHEEL_ROWS }
    : { cols: PRINT_COLS, rows: PRINT_ROWS };
}

// Which item in each category is the one you paint yourself. You buy it once
// and it stays editable -- repainting is free.
export const CUSTOM_ID = { deck: 'deck-custom', grip: 'grip-custom', wheels: 'wheel-custom' };

// --- THREE LAYERS, ONE CATALOGUE ---------------------------------------------
// A shirt, a jumper over it, and a jacket over that. The middle layer is not a
// second catalogue -- it is the same overwear list cut in two by what the
// garment IS, so every id anybody already owns stays exactly as valid as it was
// and nothing has to be migrated except which slot it hangs in.
//
// The cut is the obvious one: things you pull on go in the middle, things you
// zip up go on top. A flannel counts as a middle layer because that is how it
// is worn -- open over a tee, under a jacket -- and a gilet counts as a jacket
// because it is the outermost thing anybody wears one under.
const MID_KINDS = ['hoodie', 'sweater', 'cardigan', 'flannel'];

GEAR.mid = [
  { id: 'mid-none', name: 'NOTHING', price: 0, tag: 'shirt and jacket only', kind: 'none',
    c: ['#000', '#000', '#000'] },
].concat(GEAR.over.filter((g) => MID_KINDS.indexOf(g.kind) >= 0));
GEAR.over = GEAR.over.filter((g) => MID_KINDS.indexOf(g.kind) < 0);

// Which slot an id belongs in, for saves written before the split.
export function slotOf(id) {
  if (GEAR.mid.some((g) => g.id === id)) return 'mid';
  if (GEAR.over.some((g) => g.id === id)) return 'over';
  return null;
}

export function item(kind, id) {
  const list = GEAR[kind] || [];
  return list.find((g) => g.id === id) || list[0];
}
